### PR TITLE
Extracting report build into separate method

### PR DESCRIPTION
**Pull request by starkda**
resolution of issue https://github.com/cqfn/jpeek/issues/461
Extracted part of App.analyze method, which responsible for building report into separate method App.buildReport.
To make code simplier, added enum that represents Metrics and their meta-information.

### CODE REVIEW

**Comment by starkda** [comment]
@yegor256 could you please review it

**Comment by yegor256** [comment]
@starkda looks good! Now, try to run `mvn clean install -Pqulice` locally and see the result.

**Comment by starkda** [comment]
@yegor256 i've fixed all checkstyle issues. Now workflow supposed to pass

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
