### PR TITLE
add available CLI options to README.md

### LINKED ISSUE #460: README.md:48-50: Improve how to use section on README.md...
The puzzle `452-fc6e85e0` from #452 has to be resolved: 

https://github.com/yegor256/jpeek/blob/ab8826a691bab7f18cde3c717e5f03575781fcfd/README.md#L48-L50

The puzzle was created by paulodamaso on 21-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### LINKED ISSUE #494: README.md:48-50: Improve how to use section on README.md...
The puzzle `452-fc6e85e0` from #452 has to be resolved: 

https://github.com/cqfn/jpeek/blob/18efdffb24f021df355ce7044d22dce8f2c761a1/README.md#L48-L50

The puzzle was created by @yegor256 on 05-Feb-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by evermake**
I've added a toggle-table with a list of all CLI options (parameters) I've found in the `src/main/java/org/jpeek/Main.java`.

Closes #460, closes #494

### CODE REVIEW

**Comment by evermake** [comment]
@yegor256, could you please check, whether formulations and formatting of the table are OK. Also I'm not sure if I missed some details.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@evermake thanks!

**Pull request merged**
