### PR TITLE
Changed execution phase from package to verify and added MojoFailureE…

### PR DESCRIPTION
**Pull request by iMaks99**
…xception in App.analyze() if score less than expected ration (temporary value set as 8.0)

Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems, or leave puzzles)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed
  - Title begins with the issue's number, then a short title
  - Description begins with the issue's number, then enumerates the changes - summarized - in bulletpoints
  - Description does not contain GitHub keywords (https://help.github.com/articles/closing-issues-using-keywords/).

This article will help you understand what we are looking for: https://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by g4s8** [comment]
@paulodamaso can you please review this PR?

**Review by paulodamaso — CHANGES_REQUESTED** [review]
@iMaks99 We already have the project https://github.com/yegor256/jpeek-maven-plugin, so I think that it would be better if we move the part which relates to maven there. Also CI is failing, please fix it

**Comment by iMaks99** [comment]
This pull request relates to maven plugin only. So it can be closed now @paulodamaso

**Comment by paulodamaso** [comment]
@iMaks99 Thank you!

**Comment by 0crat** [comment]
Job `gh:cqfn/jpeek#492` is not assigned, can't get performer

**Pull request closed without merging**
