### PR TITLE
[#535] fix UnsupportedOperation Records requires ASM8

### LINKED ISSUE #535: UnsupportedOperationException: Records requires ASM8
```
Caused by: java.lang.UnsupportedOperationException: Records requires ASM8
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:111)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.jpeek.skeleton.XmlClass.iterator(XmlClass.java:89)
	at org.xembly.Directives.toCollection(Directives.java:562)
	at org.xembly.Directives.append(Directives.java:228)
	at org.jpeek.skeleton.Skeleton.xembly(Skeleton.java:192)
	at org.jpeek.skeleton.Skeleton.lambda$packages$2(Skeleton.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by pnatashap**
- fix exception UnsupportedOperation Records requires ASM8 (appeared for record class)
- tests are added for deprecated and record classes (for JDK14+) 

Fix #535 
includes https://github.com/cqfn/jpeek/pull/539

### CODE REVIEW

**Comment by pnatashap** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor status

**Comment by pnatashap** [comment]
@yegor256 please take a look. shutdown can not stop something from time to time, will check it later

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@pnatashap thanks a lot!

**Pull request merged**
